/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tahmina' at '29/05/15 5:20 PM' with Gradle 2.3
 *
 * @author tahmina, @date 29/05/15 5:20 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
